### PR TITLE
Bump OSMesa on Windows

### PR DESCRIPTION
**Pull request by banesullivan**

### CODE REVIEW

**Comment by akaszynski** [comment]
Will this be necessary with osmesa VTK wheels?

**Comment by banesullivan** [comment]
FWIW, this action is used by a handful of non-VTK graphics projects too

**Comment by larsoner** [comment]
@banesullivan where did you get the updated DLL?

I'm guessing it needs some other DLL(s) that are not present. Have you tried using DependencyWalker on it? You can see how I've done it programatically for another repo here when I had to debug:

- https://github.com/openmeeg/openmeeg/blob/main/.github/workflows/build_and_test.yml#L482-L485
- https://github.com/openmeeg/openmeeg/blob/main/build_tools/install_dependency_walker.sh

I could do something similar here if it would help figure out why the new DLL isn't working.

I have a vague recollection that this dependency chain is one reason I didn't update the MESA OpenGL DLL using the release version on the MESA website.

**Comment by larsoner** [comment]
For example [this msys/pacman url](https://packages.msys2.org/package/mingw-w64-x86_64-mesa?repo=mingw64) suggests there are a bunch of other dependencies for 23.0.1 s. You'd probably need the whole chain if you used that or a similar version...

**Comment by banesullivan** [comment]
FYI, with the new OSMesa wheels being published for linux already and soon for Windows, this action will no longer be needed for PyVista's tests and I will likely move to deprecate it or focus it entirely for the qt use case

**Pull request closed without merging**
