### PR TITLE
wrap qt app install command, add 4 more libs

### LINKED ISSUE #13: `libxcb-cursor0` oddly not getting installed
I recently had a case where a qt package of mine failed on ubuntu with this action, but adding my https://github.com/tlambert03/setup-qt-libs action solved it.  I do have a couple more libs in my action `'libdbus-1-3', 'libegl1-mesa', 'libxcb-xinput0', 'x11-utils'` ...  but after installing them one by one, none of them fixed it.  I eventually realized that it was `libxcb-cursor0` that was missing, even though it *is* in your [action.yml here](https://github.com/pyvista/setup-headless-display-action/blob/be3f59063622045c12afc9b1cde68ca89bb8aa21/action.yml#L29) .  Note how it's missing from my logs here:

```
2024-06-16T00:19:42.3632901Z ##[group]Run sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libopengl0 libegl1 libosmesa6 mesa-utils libxcb-shape0
2024-06-16T00:19:42.3634887Z [36;1msudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libopengl0 libegl1 libosmesa6 mesa-utils libxcb-shape0[0m
2024-06-16T00:19:42.3694259Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2024-06-16T00:19:42.3694742Z ##[endgroup]
2024-06-16T00:19:42.3870908Z 
```

do you think it's a yaml line length issue?  could make a PR to wrap that line.
(and, wonder how you feel about adding the others remaing libraries above... not sure whether any are critical, but it would let me forget about using my setup-qt-libs action altogether :)

### PR DESCRIPTION
**Pull request by tlambert03**
closes #13 

as a shot in the dark, this PR wraps the command to install qt-libs in `action.yml`, it also added four more libraries that are present in [setup-qt-libs](https://github.com/tlambert03/setup-qt-libs), which may be used in certain Qt applications

- `libdbus-1-3`
- `libegl1-mesa`
- `libxcb-xinput0`
- `x11-utils`

### CODE REVIEW

**Comment by tlambert03** [comment]
@larsoner ... possible that the actions aren't running due to inactivity here?

**Comment by larsoner** [comment]
Also you can see the tests are super basic... if you have widely used modules that would catch some of those new system libraries feel free to add them (but not required)

**Comment by tlambert03** [comment]
yeah, I'm afraid it's been a while since I determined the list that I used in `setup-qt-libs`... i'll dig for a moment and see if I can find a good test case, but may give up :)

**Comment by larsoner** [comment]
Hah, tests fail because the `macos-latest` now means `macos-14`. I'll open a separate PR to fix CIs while you look!

**Comment by tlambert03** [comment]
side-note, d5e79a9 bumped the action versions and changed python 3.9 to 3.10 (needed unless we want to use an older macos runner)

**Comment by tlambert03** [comment]
ah ok :) will undo here

**Comment by larsoner** [comment]
There is a conflict, I can fix it if you want or feel free to push

**Comment by tlambert03** [comment]
no worries, got it.

**Comment by larsoner** [comment]
Thanks @tlambert03 !

**Comment by tlambert03** [comment]
thanks!

**Comment by tlambert03** [comment]
will follow up with better tests in #17

**Review by farshadjanu1 — APPROVED** [review]

**Pull request merged**
